export enum Permission {
  // SUPER ADMIN
  ALL_PERMISSIONS = "ALL_PERMISSIONS",

  // PRODUCTS
  CREATE_PRODUCT = "CREATE_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",
  GET_PRODUCTS = "GET_PRODUCTS",
  GET_MY_PRODUCTS = "GET_MY_PRODUCTS",
  GET_PRODUCT = "GET_PRODUCT",
  UPDATE_PRODUCT = "UPDATE_PRODUCT",

  // ORDERS
  CREATE_ORDER = "CREATE_ORDER",
  GET_MY_ORDERS = "GET_MY_ORDERS",
  GET_ALL_ORDERS = "GET_ALL_ORDERS",

  // INVOICES
  GET_MY_INVOICES = "GET_MY_INVOICES",
  GET_INVOICE = "GET_INVOICE",
}
